networks:
  dnsnet:
    ipam:
      config:
        - subnet: 172.24.0.0/24

services:
  authoritative:
    build: ./Authoritative
    container_name: authoritative
    networks:
      dnsnet:
        ipv4_address: 172.24.0.2 # provide static ip for service

  resolver:
    build: ./Resolver
    container_name: resolver
    networks:
      dnsnet:
        ipv4_address: 172.24.0.5 # provide static ip for service

  service1:
    build: ./Service1
    container_name: service1
    dns: 172.24.0.2
    networks:
      dnsnet:
        ipv4_address: 172.24.0.3 # provide static ip for service

  service2:
    build: ./Service2
    container_name: service2
    dns: 172.24.0.2
    networks:
      dnsnet:
        ipv4_address: 172.24.0.4 # provide static ip for service
